# Generated by Django 3.2.3 on 2024-01-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiRequestCounter",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "path",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False
                    ),
                ),
                ("count", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "db_table": "api_request_counter",
            },
        ),
    ]
